"""sync started_at, completed_at columns for UserBook (final)

Revision ID: c63888ebd849
Revises: 798502d6d021
Create Date: 2025-12-12 16:37:41.147021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63888ebd849'
down_revision: Union[str, None] = '20251129_add_google_ratings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 이미 테이블이 존재하므로 중복 생성 방지
    # op.create_table('book_categories', ...)
    # op.create_table('book_views', ...)
    # op.create_table('support_ticket_answer_history', ...)
    # op.create_table('support_ticket_logs', ...)
    # SQLite는 컬럼 타입 변경을 직접 지원하지 않으므로, 아래 명령은 생략/주석 처리
    # op.alter_column('books', 'category',
    #            existing_type=sa.VARCHAR(length=100),
    #            type_=sa.String(length=255),
    #            existing_nullable=True)
    # SQLite는 unique constraint 삭제를 직접 지원하지 않으므로, 아래 명령은 생략/주석 처리
    # op.drop_constraint('uniq_books_nfc_uid', 'books', type_='unique')
    op.drop_column('books', 'authors')
    op.add_column('review_likes', sa.Column('wishlist_at', sa.DateTime(), nullable=True))
    # SQLite는 기존 테이블에 외래키 추가를 직접 지원하지 않으므로, 아래 명령은 생략/주석 처리
    # op.create_foreign_key(None, 'search_history', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('support_tickets', sa.Column('responded_by', sa.Integer(), nullable=True))
    op.add_column('support_tickets', sa.Column('responded_at', sa.DateTime(), nullable=True))
    op.alter_column('support_tickets', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OPEN', 'ANSWERED', 'CLOSED', name='supportticketstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'open'"))
    # SQLite는 기존 테이블에 외래키 추가를 직접 지원하지 않으므로, 아래 명령은 생략/주석 처리
    # op.create_foreign_key(None, 'support_tickets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # op.create_foreign_key(None, 'support_tickets', 'users', ['responded_by'], ['id'], ondelete='SET NULL')
    op.add_column('user_books', sa.Column('started_date', sa.Date(), nullable=True))
    op.add_column('user_books', sa.Column('finished_date', sa.Date(), nullable=True))
    # SQLite는 컬럼 타입 변경을 직접 지원하지 않으므로, 아래 명령은 생략/주석 처리
    # op.alter_column('user_books', 'started_at',
    #            existing_type=sa.DATE(),
    #            type_=sa.DateTime(),
    #            existing_nullable=True)
    # op.alter_column('user_books', 'completed_at',
    #            existing_type=sa.DATE(),
    #            type_=sa.DateTime(),
    #            existing_nullable=True)
    op.create_unique_constraint('uq_wishlist_user_book', 'wishlist', ['user_id', 'book_id'])
    # SQLite는 기존 테이블에 외래키 추가를 직접 지원하지 않으므로, 아래 명령은 생략/주석 처리
    # op.create_foreign_key(None, 'wishlist', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # op.create_foreign_key(None, 'wishlist', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite는 기존 테이블의 외래키 삭제를 직접 지원하지 않으므로, 아래 명령은 생략/주석 처리
    # op.drop_constraint(None, 'wishlist', type_='foreignkey')
    # op.drop_constraint(None, 'wishlist', type_='foreignkey')
    op.drop_constraint('uq_wishlist_user_book', 'wishlist', type_='unique')
    # SQLite는 컬럼 타입 변경을 직접 지원하지 않으므로, 아래 명령은 생략/주석 처리
    # op.alter_column('user_books', 'completed_at',
    #            existing_type=sa.DateTime(),
    #            type_=sa.DATE(),
    #            existing_nullable=True)
    # op.alter_column('user_books', 'started_at',
    #            existing_type=sa.DateTime(),
    #            type_=sa.DATE(),
    #            existing_nullable=True)
    op.drop_column('user_books', 'finished_date')
    op.drop_column('user_books', 'started_date')
    # SQLite는 기존 테이블의 외래키 삭제를 직접 지원하지 않으므로, 아래 명령은 생략/주석 처리
    # op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    # op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    op.alter_column('support_tickets', 'status',
               existing_type=sa.Enum('OPEN', 'ANSWERED', 'CLOSED', name='supportticketstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'open'"))
    op.drop_column('support_tickets', 'responded_at')
    op.drop_column('support_tickets', 'responded_by')
    # SQLite는 기존 테이블의 외래키 삭제를 직접 지원하지 않으므로, 아래 명령은 생략/주석 처리
    # op.drop_constraint(None, 'search_history', type_='foreignkey')
    op.drop_column('review_likes', 'wishlist_at')
    op.add_column('books', sa.Column('authors', sa.VARCHAR(length=255), nullable=True))
    op.create_unique_constraint('uniq_books_nfc_uid', 'books', ['nfc_uid'])
    # SQLite는 컬럼 타입 변경을 직접 지원하지 않으므로, 아래 명령은 생략/주석 처리
    # op.alter_column('books', 'category',
    #            existing_type=sa.String(length=255),
    #            type_=sa.VARCHAR(length=100),
    #            existing_nullable=True)
    op.drop_table('support_ticket_logs')
    op.drop_table('support_ticket_answer_history')
    op.drop_table('book_views')
    op.drop_table('book_categories')
    # ### end Alembic commands ###
