"""add wishlist_at to wishlist

Revision ID: de23d6d68f3b
Revises: c63888ebd849
Create Date: 2025-12-13 03:07:40.283354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de23d6d68f3b'
down_revision: Union[str, None] = 'c63888ebd849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_likes', sa.Column('wishlist_at', sa.DateTime(), nullable=True))
    op.add_column('user_books', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('user_books', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('wishlist', sa.Column('wishlist_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist', 'wishlist_at')
    op.drop_column('user_books', 'completed_at')
    op.drop_column('user_books', 'started_at')
    op.drop_column('review_likes', 'wishlist_at')
    # ### end Alembic commands ###
