"""remove unique constraint from isbn_13

Revision ID: 8f5e31b04d4f
Revises: febf3828a747
Create Date: 2025-12-22 21:09:57.701675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f5e31b04d4f'
down_revision: Union[str, None] = 'febf3828a747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        # books.isbn_13 unique 인덱스만 삭제
        op.drop_index('isbn_13', table_name='books')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_index('isbn_13', 'books', ['isbn_13'], unique=True)
    # ### end Alembic commands ###
